# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 581)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.field_name_combo = QtWidgets.QComboBox(self.groupBox_3)
        self.field_name_combo.setObjectName("field_name_combo")
        self.field_name_combo.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.field_name_combo)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.harvest_combo = QtWidgets.QComboBox(self.groupBox_3)
        self.harvest_combo.setObjectName("harvest_combo")
        self.harvest_combo.addItem("")
        self.harvest_combo.addItem("")
        self.harvest_combo.addItem("")
        self.harvest_combo.addItem("")
        self.harvest_combo.addItem("")
        self.harvest_combo.addItem("")
        self.harvest_combo.addItem("")
        self.harvest_combo.addItem("")
        self.harvest_combo.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.harvest_combo)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 6, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.plot_spin = QtWidgets.QSpinBox(self.groupBox)
        self.plot_spin.setMaximum(1000)
        self.plot_spin.setObjectName("plot_spin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.plot_spin)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.plant_spin = QtWidgets.QSpinBox(self.groupBox)
        self.plant_spin.setMinimum(1)
        self.plant_spin.setObjectName("plant_spin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.plant_spin)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.scan_spin = QtWidgets.QSpinBox(self.groupBox)
        self.scan_spin.setMinimum(1)
        self.scan_spin.setObjectName("scan_spin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.scan_spin)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.next_plant = QtWidgets.QPushButton(self.groupBox_4)
        self.next_plant.setObjectName("next_plant")
        self.verticalLayout_2.addWidget(self.next_plant)
        self.next_scan = QtWidgets.QPushButton(self.groupBox_4)
        self.next_scan.setObjectName("next_scan")
        self.verticalLayout_2.addWidget(self.next_scan)
        self.delete_scan = QtWidgets.QPushButton(self.groupBox_4)
        self.delete_scan.setObjectName("delete_scan")
        self.verticalLayout_2.addWidget(self.delete_scan)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_10.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scan_view = QtWidgets.QGraphicsView(self.widget_2)
        self.scan_view.setObjectName("scan_view")
        self.verticalLayout_5.addWidget(self.scan_view)
        self.horizontalLayout_10.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Leaf Scanner"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Scan Setup"))
        self.label.setText(_translate("MainWindow", "Field Name:"))
        self.field_name_combo.setItemText(0, _translate("MainWindow", "NMSU"))
        self.label_3.setText(_translate("MainWindow", "Datasheet:"))
        self.harvest_combo.setItemText(0, _translate("MainWindow", "1"))
        self.harvest_combo.setItemText(1, _translate("MainWindow", "2"))
        self.harvest_combo.setItemText(2, _translate("MainWindow", "3"))
        self.harvest_combo.setItemText(3, _translate("MainWindow", "4"))
        self.harvest_combo.setItemText(4, _translate("MainWindow", "5"))
        self.harvest_combo.setItemText(5, _translate("MainWindow", "6"))
        self.harvest_combo.setItemText(6, _translate("MainWindow", "7"))
        self.harvest_combo.setItemText(7, _translate("MainWindow", "8"))
        self.harvest_combo.setItemText(8, _translate("MainWindow", "9"))
        self.groupBox.setTitle(_translate("MainWindow", "Sample ID"))
        self.label_4.setText(_translate("MainWindow", "Plot #:"))
        self.label_5.setText(_translate("MainWindow", "Plant #:"))
        self.label_6.setText(_translate("MainWindow", "Scan #:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Actions"))
        self.next_plant.setText(_translate("MainWindow", "Next Plant"))
        self.next_scan.setText(_translate("MainWindow", "Next Scan "))
        self.delete_scan.setText(_translate("MainWindow", "Delete Scan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

